version: '3.8'

services:
  pixabay-app:
    build: .
    container_name: pixabay-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGOUSER=${MONGOUSER}
      - MONGOPASSWORD=${MONGOPASSWORD}
      - MONGOURL=${MONGOURL}
      - PIXABAY_API_KEY=${PIXABAY_API_KEY}
    volumes:
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s